apiVersion: apps/v1
kind: Deployment
metadata:
 name: postgres
 namespace: staging
spec:
 strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
   type: RollingUpdate
 replicas: 1
 selector:
   matchLabels:
     app: postgres
 template:
   metadata:
     labels:
       app: postgres
   spec:
     containers:
       - name: postgres
         image: postgres:14
         resources:
           limits:
             cpu: "1"
             memory: "2Gi"
           requests:
             cpu: "1"
             memory: "2Gi"
         ports:
           - containerPort: 5432
         envFrom:
           - configMapRef:
               name: postgresql-cm
         volumeMounts:
           - mountPath: /var/lib/postgresql/pgdata
             name: postgredb
     volumes:
       - name: postgredb
         persistentVolumeClaim:
           claimName: postgresql-pv
