apiVersion: v1
kind: Service
metadata:
  labels:
    app: server-service
  name: server-service
  namespace: staging
spec:
  ports:
  - name: server-service
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30002
  selector:
    app: server-trippr
  type: NodePort     
