apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trippr-staging-ingress
  namespace: staging
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "staging-trippr-static-ip"
spec:
  rules:
  - host: yourbus.co.in
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: wesite-service-loadbal
            port:
              number: 80
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: server-service
            port:
              number: 3000