apiVersion: v1
kind: Service
metadata:
  name: wesite-service-loadbal
  namespace: staging
spec:
  type: LoadBalancer
  selector:
    app: trippr-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80